controller:
  config:
    use-proxy-protocol: true
    use-forwarded-headers: true
    compute-full-forwarded-for: true
  service:
    annotations:
      load-balancer.hetzner.cloud/name: "lb-terraform"
      load-balancer.hetzner.cloud/location: "nbg1"
      load-balancer.hetzner.cloud/use-private-ip: true
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
      load-balancer.hetzner.cloud/disable-private-ingress: true